"""Render analysis into an HTML email body (and a plain-text fallback)."""

from __future__ import annotations

from datetime import datetime

from jinja2 import Environment

from .analyzer import NicheInsights, detect_hooks

_ENV = Environment(autoescape=True)


def _fmt(n: float) -> str:
    n = int(n)
    if n >= 10_000_000:
        return f"{n / 10_000_000:.1f}Cr"  # crore, India-friendly
    if n >= 100_000:
        return f"{n / 100_000:.1f}L"  # lakh
    if n >= 1_000:
        return f"{n / 1_000:.1f}K"
    return str(n)


_ENV.filters["fmt"] = _fmt


def _hooks_filter(title: str) -> str:
    hooks = detect_hooks(title)
    return ", ".join(hooks) if hooks else "—"


_ENV.filters["hooks"] = _hooks_filter

_TEMPLATE = _ENV.from_string(
    """
<div style="font-family:-apple-system,Segoe UI,Roboto,Helvetica,Arial,sans-serif;color:#1a1a1a;max-width:720px;margin:0 auto;">
  <h1 style="font-size:22px;margin:0 0 4px;">📺 YouTube Niche Report</h1>
  <p style="color:#666;margin:0 0 20px;">{{ date }}</p>

  {% for ins in niches %}
  <div style="border:1px solid #eee;border-radius:12px;padding:18px;margin-bottom:24px;">
    <h2 style="font-size:18px;margin:0 0 2px;text-transform:capitalize;">{{ ins.niche }}</h2>
    <p style="color:#666;margin:0 0 14px;font-size:13px;">Top {{ ins.total_creators }} Indian creators analyzed</p>

    <table style="width:100%;border-collapse:collapse;font-size:13px;margin-bottom:16px;">
      <tr style="background:#fafafa;">
        <td style="padding:8px;border:1px solid #eee;"><b>Shorts</b> avg views</td>
        <td style="padding:8px;border:1px solid #eee;">{{ ins.shorts_avg_views | fmt }}</td>
        <td style="padding:8px;border:1px solid #eee;"><b>Long-form</b> avg views</td>
        <td style="padding:8px;border:1px solid #eee;">{{ ins.long_avg_views | fmt }}</td>
      </tr>
      <tr>
        <td style="padding:8px;border:1px solid #eee;">Shorts engagement</td>
        <td style="padding:8px;border:1px solid #eee;">{{ '%.2f%%' % (ins.shorts_avg_engagement * 100) }}</td>
        <td style="padding:8px;border:1px solid #eee;">Long-form engagement</td>
        <td style="padding:8px;border:1px solid #eee;">{{ '%.2f%%' % (ins.long_avg_engagement * 100) }}</td>
      </tr>
    </table>

    {% if ins.hook_frequency %}
    <h3 style="font-size:14px;margin:14px 0 6px;">🎣 Hook patterns in top videos</h3>
    <p style="margin:0 0 12px;font-size:13px;">
      {% for name, count in ins.hook_frequency %}
        <span style="display:inline-block;background:#eef;border-radius:6px;padding:3px 8px;margin:2px;">{{ name }} · {{ count }}</span>
      {% endfor %}
    </p>
    {% endif %}

    {% if ins.topic_keywords %}
    <h3 style="font-size:14px;margin:14px 0 6px;">🔑 Recurring topic keywords</h3>
    <p style="margin:0 0 12px;font-size:13px;color:#333;">
      {% for word, count in ins.topic_keywords %}{{ word }}{% if not loop.last %} · {% endif %}{% endfor %}
    </p>
    {% endif %}

    <h3 style="font-size:14px;margin:16px 0 6px;">🔥 Top long-form videos</h3>
    <ol style="margin:0 0 12px;padding-left:20px;font-size:13px;line-height:1.5;">
      {% for v in ins.top_long[:6] %}
      <li>
        <a href="{{ v.url }}" style="color:#0b5;text-decoration:none;">{{ v.title }}</a><br>
        <span style="color:#666;">{{ v.views | fmt }} views · {{ '%.1f%%' % (v.engagement_rate * 100) }} engagement · hooks: {{ v.title | hooks }}</span>
      </li>
      {% endfor %}
    </ol>

    <h3 style="font-size:14px;margin:16px 0 6px;">⚡ Top Shorts</h3>
    <ol style="margin:0 0 12px;padding-left:20px;font-size:13px;line-height:1.5;">
      {% for v in ins.top_shorts[:6] %}
      <li>
        <a href="{{ v.url }}" style="color:#0b5;text-decoration:none;">{{ v.title }}</a><br>
        <span style="color:#666;">{{ v.views | fmt }} views · {{ '%.1f%%' % (v.engagement_rate * 100) }} engagement · hooks: {{ v.title | hooks }}</span>
      </li>
      {% endfor %}
    </ol>

    {% if ins.llm_summary %}
    <h3 style="font-size:14px;margin:16px 0 6px;">🧠 Why these work (AI analysis)</h3>
    <div style="font-size:13px;line-height:1.6;white-space:pre-wrap;background:#fafafa;border-radius:8px;padding:12px;">{{ ins.llm_summary }}</div>
    {% endif %}

    {% if ins.notes %}
    <h3 style="font-size:14px;margin:16px 0 6px;">📝 Notes</h3>
    <ul style="margin:0;padding-left:20px;font-size:13px;line-height:1.5;color:#444;">
      {% for note in ins.notes %}<li>{{ note }}</li>{% endfor %}
    </ul>
    {% endif %}
  </div>
  {% endfor %}

  <p style="color:#999;font-size:12px;border-top:1px solid #eee;padding-top:12px;">
    Data: YouTube Data API v3 (region IN). Shares &amp; saves are not exposed by the API,
    so engagement here = (likes + comments) / views. Generated by your YouTube Agent.
  </p>
</div>
"""
)


def build_html(niches: list[NicheInsights]) -> str:
    return _TEMPLATE.render(
        niches=niches,
        date=datetime.now().strftime("%A, %d %B %Y"),
    )


def build_text(niches: list[NicheInsights]) -> str:
    lines = ["YouTube Niche Report", datetime.now().strftime("%A, %d %B %Y"), ""]
    for ins in niches:
        lines.append(f"=== {ins.niche.upper()} ({ins.total_creators} creators) ===")
        lines.append(
            f"Shorts avg views: {_fmt(ins.shorts_avg_views)} | "
            f"Long avg views: {_fmt(ins.long_avg_views)}"
        )
        if ins.hook_frequency:
            lines.append(
                "Hooks: " + ", ".join(f"{n} ({c})" for n, c in ins.hook_frequency)
            )
        lines.append("Top long-form:")
        for v in ins.top_long[:5]:
            lines.append(f"  - {v.title} [{_fmt(v.views)} views] {v.url}")
        lines.append("Top shorts:")
        for v in ins.top_shorts[:5]:
            lines.append(f"  - {v.title} [{_fmt(v.views)} views] {v.url}")
        if ins.llm_summary:
            lines.append("Why these work:")
            lines.append(ins.llm_summary)
        lines.append("")
    return "\n".join(lines)


def subject_line(niches: list[NicheInsights]) -> str:
    names = ", ".join(n.niche for n in niches)
    return f"📺 YouTube Report — {names} — {datetime.now():%d %b %Y}"
